# Generated by Django 5.0.7 on 2024-08-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooksmodel',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ebooksmodel',
            name='pages',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ebooksmodel',
            name='summary',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ebooksmodel',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
