# Generated by Django 5.0.7 on 2024-08-24 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebook_app', '0002_alter_ebooksmodel_category_alter_ebooksmodel_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebooksmodel',
            name='category',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='ebooksmodel',
            name='pages',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='ebooksmodel',
            name='summary',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='ebooksmodel',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
